version: "3.8"

services:
  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0
    container_name: "elasticsearch-exporter"
    command:
      - '--es.uri=http://10.0.0.7:9201'
    restart: always
    ports:
      - "9114:9114"
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      resources:
        limits:
          memory: 4g
    extra_hosts:
      - "docker:10.0.0.95"
      - "one:10.0.0.98"
      - "two:10.0.0.99"
      - "three:10.0.0.93"