version: '2.1'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.6.1'
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2183:2181"
    volumes:
      - zoo_data:/bitnami/zookeeper/data
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 2g

  kafka:
    image: 'bitnami/kafka:2.5.0'
    container_name: kafka
    restart: always
    ports:
      - "9089:9092"
    volumes:
      - kafka_data:/bitnami/kafka/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:9089
    mem_limit: 2g
    depends_on:
      - zookeeper

volumes:
  zoo_data:
  kafka_data: