version: '2.1'

services:
  portainer:
    image: "portainer/portainer-ce:2.19.5"
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 2g

volumes:
  data: