version: '2'

services:
  redis:
    image: bitnami/redis:7.4.2
    container_name: redis
    restart: unless-stopped
    ports:
      - '6390:6379'
    volumes:
      - 'data:/bitnami/redis/data'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - 'REDIS_PASSWORD=Rongshu@2024'
    mem_limit: 4g

volumes:
  data: