version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node-exporter
    restart: always
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    deploy:
      resources:
        limits:
          memory: 4g
    extra_hosts:
      - "docker:10.0.0.95"
      - "one:10.0.0.98"
      - "two:10.0.0.99"
      - "three:10.0.0.93"